spring:
  application:
    name: microservice-gateway-zuul
server:
    port: 8040
eureka:
    client:
      service-url:
        defaultZone: http://localhost:9527/eureka/
    instance:
      prefer-ip-address: true
feign:
   hystrix:
      enabled:true

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000